---
- name: Create directory
  file:
    dest: "{{ jolokia_parent_dir }}"
    mode: 0755
    state: directory

- name: Download the archive
  get_url:
    url: "{{ jolokia_url }}"
    dest: "{{ jolokia_parent_dir }}/{{ jolokia_file_name }}"
    timeout: 30

- name: Set permissions to the file
  file:
    path: "{{ jolokia_parent_dir }}/{{ jolokia_file_name }}"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
